### ISSUE TITLE
Can't log in - Blank page 

### ISSUE THREAD

**Issue by Morpheus907** [devhotteok/TwitchLink#220]
I went to open up Twitchlink after about a month somehow it lost my login credentials, No Problem. Until there was. I hit log in button that is supposed to take me to Twitch.tv/login page. However that page is blank. Not a word on it  so I hit refresh, after some time I get a error that says this . 
"Traceback (most recent call last):
  File "PyQt6\uic\ui_file.py", line 35, in __init__
  File "xml\etree\ElementTree.py", line 1218, in parse
  File "xml\etree\ElementTree.py", line 569, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Windows/system32/resources/ui/mainWindow.ui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Core\Ui.py", line 40, in load
  File "PyQt6\uic\load_ui.py", line 54, in loadUiType
  File "PyQt6\uic\Compiler\compiler.py", line 101, in compileUi
  File "PyQt6\uic\uiparser.py", line 995, in parse
  File "PyQt6\uic\ui_file.py", line 37, in __init__
  File "PyQt6\uic\ui_file.py", line 92, in _raise_exception
PyQt6.uic.exceptions.UIFileException: C:/Windows/system32/resources/ui/mainWindow.ui: invalid Qt Designer file: [Errno 2] No such file or directory: 'C:/Windows/system32/resources/ui/mainWindow.ui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TwitchLink.py", line 15, in <module>
  File "TwitchLink.py", line 8, in TwitchLink
  File "Ui\MainWindow.py", line 17, in __init__
  File "Core\Ui.py", line 42, in load
TypeError: Exceptions.FileSystemError.__init__() missing 1 required positional argument: 'target'
" 
This is after uninstalling and re-installing Twitchlink  including all (Twitchlink related) folders in the AppData folders.
Thank you for any assistance you can give me

**Comment by devhotteok** [comment]
I've applied a fix for the login issue. If the problem persists, please feel free to open a new issue.
Also, for the occasional program crashes, I believe that this might be related to PyQt itself. I will investigate this further.
