### ISSUE TITLE
다운로드 안됨

### ISSUE THREAD

**Issue by hyperQ2** [devhotteok/TwitchLink#23]
구독자 다운보기의 경우
ts 파일 다운로드까지는 성공하는데 완성 파일로 묶질못함.

**Comment by hyperQ2** [comment]
![캡처222](https://user-images.githubusercontent.com/105331850/167757706-ded8999c-2067-4ba1-8ef3-e20325ee7c07.PNG)

경로 전부 영어로 변환도 해봤고 용량 부족 없으며 관리자권한으로도 실행해 보았음.

**Comment by devhotteok** [comment]
Please attach the log record. You can check it by clicking the button in the upper right corner of the download screen.

**Comment by hyperQ2** [comment]
> [2022-05-11 11:58:31,009][INFO] Subprocess ended with exit code 1.
[2022-05-11 11:58:31,009][ERROR][Setup.py:45] File System Error
Traceback (most recent call last):
  File "Download\Downloader\Engine\Setup.py", line 43, in run
  File "Download\Downloader\Engine\Video\Video.py", line 27, in download
  File "Download\Downloader\Engine\Video\Video.py", line 131, in encode
  File "Download\Downloader\FFmpeg\OutputReader.py", line 43, in _readWithLogs
  File "Download\Downloader\FFmpeg\OutputReader.py", line 52, in checkError
Core.GlobalExceptions.Exceptions.FileSystemError: File System Error
[2022-05-11 11:58:31,009][INFO] Download Failed

**Comment by devhotteok** [comment]
It seems that your Windows user account is not an administrator, or you may not be authorized to use that path for some other reason. Select a different path to save the file.

**Comment by hyperQ2** [comment]
> It seems that your Windows user account is not an administrator, or you may not be authorized to use that path for some other reason. Select a different path to save the file.

관리자 계정이며 앱도 관리자 권한으로 실행했으나 안됨.

**Comment by hyperQ2** [comment]
원인을 찾아냄. 기본으로 설정된 폴더가 아니면 다운로드 되지않음. twitchlink 폴더에만 저장됨.
