### ISSUE TITLE
Subprocess Deadlock

### ISSUE THREAD

**Issue by LamAnLeTran** [devhotteok/TwitchLink#68]
Live download stream, after click stop recording, recieve error occur message and the file is corrupted.
this happened many time, log of the file:
frame=437612 fps= 60 q=-1.0 size= 2817536kB time=02:01:41.18 bitrate=3161.3kbits/s speed=   1x    
frame=437732 fps= 60 q=-1.0 size= 2818304kB time=02:01:43.18 bitrate=3161.3kbits/s speed=   1x    
[2023-02-28 13:47:43,494][WARNING] [ACTION] Cancel
frame=437852 fps= 60 q=-1.0 size= 2819072kB time=02:01:45.18 bitrate=3161.3kbits/s speed=   1x    
[2023-02-28 13:47:53,533][ERROR][OutputReader.py:46] Unable to read output properly.
[2023-02-28 13:47:53,534][ERROR][OutputReader.py:47] I/O operation on closed file.
Traceback (most recent call last):
  File "Download\Downloader\FFmpeg\OutputReader.py", line 40, in _readWithLogs
ValueError: I/O operation on closed file.
[2023-02-28 13:47:53,550][INFO] Subprocess was unresponsive and forced to terminate.
[2023-02-28 13:47:53,550][INFO] Subprocess ended with exit code 1.
[2023-02-28 13:47:53,551][ERROR][Setup.py:54] Unexpected Error
returnCode: 1
output: frame=437852 fps= 60 q=-1.0 size= 2819072kB time=02:01:45.18 bitrate=3161.3kbits/s speed=   1x    
Traceback (most recent call last):
  File "Download\Downloader\Engine\Setup.py", line 52, in run
  File "Download\Downloader\Engine\Stream\Stream.py", line 25, in download
  File "Download\Downloader\FFmpeg\OutputReader.py", line 52, in _readWithLogs
  File "Download\Downloader\FFmpeg\OutputReader.py", line 60, in checkError
Download.Downloader.FFmpeg.Exceptions.Exceptions.UnexpectedError: Unexpected Error
returnCode: 1
output: frame=437852 fps= 60 q=-1.0 size= 2819072kB time=02:01:45.18 bitrate=3161.3kbits/s speed=   1x    

[2023-02-28 13:47:53,553][INFO] Download Failed
[2023-02-28 13:47:53,553][WARNING] Download failed for the following reason.
[2023-02-28 13:47:53,553][ERROR][Setup.py:75] Unexpected Error
returnCode: 1
output: frame=437852 fps= 60 q=-1.0 size= 2819072kB time=02:01:45.18 bitrate=3161.3kbits/s speed=   1x    
NoneType: None

**Comment by devhotteok** [comment]
I changed the version of the subprocess.
This issue is closed because it is an internal issue of the subprocess.
If the same issue persists, please create a new issue.
